import { useEffect, useState } from 'react'
import { Activity, ArrowUpRight, BarChart3, Bell, BrainCircuit, Check, ChevronDown, CircleHelp, CloudUpload, Database, Download, Droplets, Globe2, Layers3, Leaf, Map, Menu, MoreHorizontal, Play, Radio, ScanSearch, Settings2, ShieldAlert, Sparkles, Timer, TrendingUp, TreePine, Waves, X, Zap } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import './App.css'

type Scenario = { id: string; name: string; location: string; date: string; type: string; code: string; accent: string; stats: { label: string; value: string; trend: string }[] }
const scenarios: Scenario[] = [
  { id: 'agri', name: 'Central Valley crop stress', location: 'Fresno County, California', date: '18 Aug 2024', type: 'Agriculture', code: 'AG-042', accent: '#8bd450', stats: [{ label: 'Vegetation', value: '63.8%', trend: '+4.2%' }, { label: 'Stress detected', value: '12.4%', trend: '-2.1%' }, { label: 'Confidence', value: '94.6%', trend: '+1.8%' }] },
  { id: 'water', name: 'Lake Mead water change', location: 'Clark County, Nevada', date: '02 Sep 2024', type: 'Water Monitoring', code: 'WM-118', accent: '#4cc8e8', stats: [{ label: 'Water area', value: '38.2%', trend: '-6.8%' }, { label: 'Change detected', value: '8.7%', trend: '+3.4%' }, { label: 'Confidence', value: '96.1%', trend: '+0.7%' }] },
  { id: 'urban', name: 'Metro growth corridor', location: 'Bengaluru, India', date: '11 Jul 2024', type: 'Urban Change', code: 'UC-073', accent: '#f4b34d', stats: [{ label: 'Urban area', value: '29.4%', trend: '+11.2%' }, { label: 'New surface', value: '4.6%', trend: '+2.8%' }, { label: 'Confidence', value: '91.8%', trend: '+2.4%' }] },
  { id: 'flood', name: 'River delta flood extent', location: 'Satkhira, Bangladesh', date: '27 Sep 2024', type: 'Disaster Monitoring', code: 'DM-206', accent: '#ec6b68', stats: [{ label: 'Affected area', value: '17.9%', trend: '+9.6%' }, { label: 'Water spread', value: '23.1%', trend: '+12.5%' }, { label: 'Confidence', value: '97.3%', trend: '+3.1%' }] },
]
const pipeline = [{ label: 'Preprocess', icon: Layers3, detail: 'Cloud mask + normalize' }, { label: 'Features', icon: ScanSearch, detail: '18 spectral bands' }, { label: 'Reduce', icon: BarChart3, detail: 'PCA -> 4 dimensions' }, { label: 'QML encode', icon: BrainCircuit, detail: 'Angle encoding' }, { label: 'Classify', icon: Sparkles, detail: 'Variational circuit' }]
const chartData = [{ month: 'Apr', qml: 87.8, classical: 84.2 }, { month: 'May', qml: 89.4, classical: 85.6 }, { month: 'Jun', qml: 91.2, classical: 86.8 }, { month: 'Jul', qml: 93.1, classical: 87.4 }, { month: 'Aug', qml: 94.6, classical: 88.1 }, { month: 'Sep', qml: 95.2, classical: 89.0 }]
const composition = [{ name: 'Vegetation', value: 48, color: '#8bd450' }, { name: 'Water', value: 18, color: '#4cc8e8' }, { name: 'Urban', value: 21, color: '#f4b34d' }, { name: 'Other', value: 13, color: '#69748a' }]

function App() {
  const [activeScenario, setActiveScenario] = useState(scenarios[0]); const [analysisType, setAnalysisType] = useState('Agriculture'); const [activeNav, setActiveNav] = useState('Overview'); const [isRunning, setIsRunning] = useState(false); const [completed, setCompleted] = useState(true); const [mobileNav, setMobileNav] = useState(false); const [split, setSplit] = useState(58); const [uploadedImage, setUploadedImage] = useState('')
  useEffect(() => {
    const picker = document.createElement('input'); picker.type = 'file'; picker.accept = 'image/*'; picker.style.display = 'none'; picker.setAttribute('aria-label', 'Upload satellite image')
    const uploadButton = document.querySelector('.upload-button')
    const handleFile = () => picker.click()
    const handleUpload = () => { const file = picker.files?.[0]; if (!file) return; const imageUrl = URL.createObjectURL(file); const signal = file.size % 10; setUploadedImage(imageUrl); setActiveScenario({ id: 'upload', name: file.name.replace(/\.[^/.]+$/, ''), location: 'Uploaded scene · local analysis', date: new Date().toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }), type: analysisType, code: 'LOCAL-001', accent: '#8bd450', stats: [{ label: 'Detected area', value: `${52 + signal}.4%`, trend: '+4.8%' }, { label: 'Change detected', value: `${8 + signal}.2%`, trend: '+2.6%' }, { label: 'Confidence', value: `${(90 + signal / 10).toFixed(1)}%`, trend: '+1.4%' }] }); setCompleted(false); setIsRunning(true); window.setTimeout(() => { setIsRunning(false); setCompleted(true) }, 1800) }
    uploadButton?.addEventListener('click', handleFile); picker.addEventListener('change', handleUpload); document.body.appendChild(picker)
    return () => { uploadButton?.removeEventListener('click', handleFile); picker.removeEventListener('change', handleUpload); picker.remove(); if (uploadedImage) URL.revokeObjectURL(uploadedImage) }
  }, [analysisType])
  useEffect(() => { const map = document.querySelector<HTMLElement>('.satellite-art'); if (map && uploadedImage) { map.style.backgroundImage = `linear-gradient(rgba(20, 48, 38, .18), rgba(20, 48, 38, .18)), url(${uploadedImage})`; map.style.backgroundSize = 'cover'; map.style.backgroundPosition = 'center' } }, [uploadedImage])
  const chooseScenario = (scenario: Scenario) => { setActiveScenario(scenario); setAnalysisType(scenario.type); setCompleted(true) }
  const runAnalysis = () => { setIsRunning(true); setCompleted(false); window.setTimeout(() => { setIsRunning(false); setCompleted(true) }, 1800) }
  const downloadReport = () => { const report = `QUANTUM EARTHVISION / ANALYSIS REPORT\n\nScenario: ${activeScenario.name}\nLocation: ${activeScenario.location}\nImage date: ${activeScenario.date}\nAnalysis: ${activeScenario.type}\nModel: Quantum Kernel Classifier (simulation)\nConfidence: ${activeScenario.stats[2].value}\nDetected change: ${activeScenario.stats[1].value}\n\nGenerated by Quantum EarthVision demo mode.`; const url = URL.createObjectURL(new Blob([report], { type: 'text/plain' })); const link = document.createElement('a'); link.href = url; link.download = `${activeScenario.code}-earthvision-report.txt`; link.click(); URL.revokeObjectURL(url) }
  const navPrimary: [string, any][] = [['Overview', Activity], ['Satellite Analysis', ScanSearch], ['Agriculture', Leaf], ['Water', Waves], ['Urban', BuildingIcon], ['Disaster', ShieldAlert]]
  const navSecondary: [string, any][] = [['QML Model', BrainCircuit], ['Reports', BarChart3]]
  return <div className="app-shell">
    <aside className={`sidebar ${mobileNav ? 'open' : ''}`}><div className="brand"><div className="brand-mark"><Globe2 size={19} /></div><div><strong>Quantum</strong><span>EarthVision</span></div><button className="icon-button close-nav" onClick={() => setMobileNav(false)}><X size={18} /></button></div><div className="workspace-select"><div><small>WORKSPACE</small><span>North America Ops</span></div><ChevronDown size={16} /></div><nav><p className="nav-label">WORKSPACE</p>{navPrimary.map(([label, Icon]) => <button key={label} className={activeNav === label ? 'active' : ''} onClick={() => { setActiveNav(label); setMobileNav(false) }}><Icon size={17} /><span>{label}</span>{label === 'Satellite Analysis' && <span className="nav-badge">4</span>}</button>)}<p className="nav-label nav-label-model">PLATFORM</p>{navSecondary.map(([label, Icon]) => <button key={label} className={activeNav === label ? 'active' : ''} onClick={() => setActiveNav(label)}><Icon size={17} /><span>{label}</span></button>)}</nav><div className="sidebar-bottom"><div className="model-status"><span className="status-dot"></span><div><strong>QML engine online</strong><small>Simulator · 4 qubits</small></div><MoreHorizontal size={16} /></div><button className="user-row"><div className="avatar">MK</div><div><strong>Maria Kline</strong><small>Data scientist</small></div><Settings2 size={16} /></button></div></aside>
    <main className="main-content"><header className="topbar"><button className="mobile-menu icon-button" onClick={() => setMobileNav(true)}><Menu size={20} /></button><div className="breadcrumbs"><span>Workspace</span><span>/</span><strong>{activeNav}</strong></div><div className="top-actions"><div className="live-pill"><span></span>LIVE DATA</div><button className="icon-button notification"><Bell size={18} /><i></i></button><div className="top-avatar">MK</div></div></header><div className="content-wrap">
      <section className="page-heading"><div><div className="eyebrow"><span className="eyebrow-line"></span>EARTH OBSERVATION INTELLIGENCE</div><h1>Good morning, Maria <span className="wave">✦</span></h1><p>Turn complex satellite signals into decisions you can act on.</p></div><div className="heading-actions"><button className="secondary-button"><CircleHelp size={16} />Guide</button><button className="primary-button" onClick={downloadReport}><Download size={16} />Export report</button></div></section>
      <section className="scenario-strip"><div className="strip-heading"><div><span className="section-kicker"><Database size={14} /> DATA LIBRARY</span><h2>Select a satellite dataset</h2></div><button className="upload-button"><CloudUpload size={16} /> Upload imagery</button></div><div className="scenario-list">{scenarios.map((scenario) => <button key={scenario.id} className={`scenario-card ${activeScenario.id === scenario.id ? 'selected' : ''}`} onClick={() => chooseScenario(scenario)} style={{ '--scenario-accent': scenario.accent } as React.CSSProperties}><div className={`thumb thumb-${scenario.id}`}><span>{scenario.id === 'agri' ? 'NDVI' : scenario.id === 'water' ? 'MNDWI' : scenario.id === 'urban' ? 'NDBI' : 'SAR'}</span><div className="thumb-grid"></div></div><div className="scenario-meta"><div className="scenario-title"><strong>{scenario.name}</strong>{activeScenario.id === scenario.id && <Check size={14} />}</div><span>{scenario.location}</span><small>{scenario.date} · {scenario.code}</small></div></button>)}</div></section>
      <section className="analysis-config"><div className="config-heading"><div><span className="section-kicker"><Map size={14} /> ANALYSIS CONFIGURATION</span><h2>Choose an application</h2></div><div className="mode-label"><span className="pulse-dot"></span>QML simulation mode</div></div><div className="config-row"><div className="analysis-tabs">{[['Agriculture', Leaf], ['Water Monitoring', Droplets], ['Urban Change', BuildingIcon], ['Disaster Monitoring', ShieldAlert]].map(([label, Icon]) => <button key={label as string} className={analysisType === label ? 'selected' : ''} onClick={() => setAnalysisType(label as string)}><Icon size={17} /><span>{label as string}</span></button>)}</div><button className="run-button" onClick={runAnalysis} disabled={isRunning}>{isRunning ? <><span className="spinner"></span>Processing QML...</> : <><Play size={16} fill="currentColor" />Run analysis</>}</button></div></section>
      <section className="pipeline"><div className="pipeline-title"><div><span className="section-kicker"><Zap size={14} /> PROCESSING PIPELINE</span><h2>From pixel to prediction</h2></div><span className="pipeline-caption">{completed ? 'Analysis complete' : 'Encoding features...'}</span></div><div className="pipeline-steps">{pipeline.map((step, index) => <div className={`pipeline-step ${completed || (isRunning && index <= 2) ? 'done' : ''}`} key={step.label}><div className="step-icon"><step.icon size={18} /></div><div><strong>{step.label}</strong><small>{step.detail}</small></div>{index < pipeline.length - 1 && <div className="connector"><span></span></div>}</div>)}</div></section>
      <div className="dashboard-grid"><section className="visual-panel panel"><div className="panel-header"><div><span className="section-kicker"><Radio size={14} /> DETECTION VIEW</span><h2>{activeScenario.name}</h2><p>{activeScenario.location} · {activeScenario.date} · Sentinel-2 L2A</p></div><button className="icon-button"><MoreHorizontal size={19} /></button></div><div className="map-view"><div className="map-toolbar"><button className="map-control active">Detection</button><button className="map-control">True color</button><button className="map-control">Features</button></div><div className="coordinates"><span>36° 44' 13.2&quot; N</span><span>119° 46' 22.8&quot; W</span></div><div className={`satellite-art art-${activeScenario.id}`} style={{ '--split': `${split}%` } as React.CSSProperties}><div className="scanline"></div><div className="overlay-label overlay-one">{activeScenario.id === 'flood' ? 'FLOOD EXTENT' : activeScenario.id === 'urban' ? 'NEW DEVELOPMENT' : activeScenario.id === 'water' ? 'SHORELINE CHANGE' : 'CROP STRESS'}</div><div className="overlay-shape shape-a"></div><div className="overlay-shape shape-b"></div><div className="overlay-shape shape-c"></div><div className="split-image"></div><input className="split-slider" type="range" min="20" max="80" value={split} onChange={(event) => setSplit(Number(event.target.value))} aria-label="Compare image split" /><div className="split-handle" style={{ left: `${split}%` }}><span></span></div></div><div className="map-legend"><span><i className="legend-green"></i> Detected region</span><span><i className="legend-yellow"></i> Watch area</span><span><i className="legend-cyan"></i> Water</span><div className="scale">2 km <span></span></div></div></div><div className="visual-footer"><span><i className="status-dot"></i> Overlay confidence <strong>{activeScenario.stats[2].value}</strong></span><span>Swipe to compare <ArrowUpRight size={14} /></span></div></section>
        <section className="metrics-panel panel"><div className="panel-header"><div><span className="section-kicker"><TrendingUp size={14} /> DECISION METRICS</span><h2>Analysis summary</h2></div><span className="live-tag">UPDATED NOW</span></div><div className="metric-list">{activeScenario.stats.map((stat, index) => <div className="metric-row" key={stat.label}><div className={`metric-icon metric-${index}`}>{index === 0 ? <TreePine size={17} /> : index === 1 ? <Activity size={17} /> : <Sparkles size={17} />}</div><div className="metric-name"><span>{stat.label}</span><small>{index === 0 ? 'Current classification' : index === 1 ? 'Compared to baseline' : 'QML prediction'}</small></div><strong>{stat.value}</strong><span className={`metric-trend ${index === 1 && activeScenario.id !== 'agri' ? 'negative' : ''}`}>{stat.trend}</span></div>)}</div><div className="confidence-box"><div><span>MODEL CONFIDENCE</span><strong>{activeScenario.stats[2].value}</strong></div><div className="confidence-ring"><svg viewBox="0 0 40 40"><circle cx="20" cy="20" r="16" /><circle className="progress" cx="20" cy="20" r="16" /></svg><Check size={13} /></div></div><div className="metric-note"><BrainCircuit size={15} /><span>Quantum Kernel Classifier · 4 qubits<br /><b>Demo metric</b> based on calibrated simulator output</span></div></section></div>
      <div className="lower-grid"><section className="panel chart-panel"><div className="panel-header"><div><span className="section-kicker"><BarChart3 size={14} /> MODEL PERFORMANCE</span><h2>QML vs classical accuracy</h2></div><div className="chart-legend"><span><i className="legend-qml"></i>QML</span><span><i className="legend-classical"></i>Classical</span></div></div><div className="chart-wrap"><ResponsiveContainer width="100%" height={200}><AreaChart data={chartData} margin={{ top: 12, right: 8, left: -22, bottom: 0 }}><defs><linearGradient id="qmlFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8bd450" stopOpacity={0.22} /><stop offset="100%" stopColor="#8bd450" stopOpacity={0} /></linearGradient></defs><CartesianGrid stroke="#26303f" vertical={false} /><XAxis dataKey="month" axisLine={false} tickLine={false} tick={{ fill: '#718096', fontSize: 11 }} /><YAxis domain={[80, 100]} axisLine={false} tickLine={false} tick={{ fill: '#718096', fontSize: 11 }} tickFormatter={(value) => `${value}%`} /><Tooltip contentStyle={{ background: '#19212c', border: '1px solid #334153', borderRadius: 6, color: '#fff', fontSize: 12 }} /><Area type="monotone" dataKey="qml" stroke="#8bd450" fill="url(#qmlFill)" strokeWidth={2} /><Area type="monotone" dataKey="classical" stroke="#4cc8e8" fill="none" strokeWidth={2} strokeDasharray="4 4" /></AreaChart></ResponsiveContainer></div><div className="chart-foot"><span>Validation accuracy · last 6 runs</span><strong>+6.2% <small>QML advantage</small></strong></div></section><section className="panel composition-panel"><div className="panel-header"><div><span className="section-kicker"><Layers3 size={14} /> CLASSIFICATION</span><h2>Land cover composition</h2></div><button className="icon-button"><MoreHorizontal size={19} /></button></div><div className="composition-body"><div className="donut"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={composition} dataKey="value" innerRadius={47} outerRadius={67} paddingAngle={3} stroke="none">{composition.map((item) => <Cell key={item.name} fill={item.color} />)}</Pie></PieChart></ResponsiveContainer><div><strong>100%</strong><span>classified</span></div></div><div className="composition-list">{composition.map((item) => <div key={item.name}><span><i style={{ background: item.color }}></i>{item.name}</span><strong>{item.value}%</strong></div>)}</div></div><div className="composition-foot"><span><Timer size={14} />Inference time</span><strong>1.24s <small>↓ 38% vs classical</small></strong></div></section></div>
      <footer className="app-footer"><span><span className="footer-orb"></span> Quantum EarthVision <small>v0.9.4 · Prototype</small></span><span>Built for resilient decisions</span></footer>
    </div></main></div>
}
function BuildingIcon({ size = 18 }: { size?: number }) { return <span className="building-icon" style={{ width: size, height: size }}><span></span><span></span><span></span></span> }
export default App
